Add a .sh file for msys
hust-open-atom-club/hustmirror-cli pull request #34
Opened 2024-10-10 10:57 UTC by xb-Bogger

2024-10-11 07:33 UTC, jxlpzqc requested changes

2024-10-11 07:33 UTC, jxlpzqc commented on src/mirrors/msys2.sh
> +    source_os_release
请修改缩进以满足项目的 [Coding Style](https://github.com/hust-open-atom-club/hustmirror-cli/blob/master/README.md#styles)

2024-10-11 09:54 UTC, xb-Bogger commented on src/mirrors/msys2.sh
> +    source_os_release
好了，我已在每个语句前添加tab(tabsize=4)，以保证缩进风格统一。没有注意到Coding styles的要求，抱歉。

2025-01-22 02:22 UTC, tttturtle-russ commented on src/mirrors/msys2.sh
> +    _msys2_config_file="/etc/pacman.d/mirrorlist.msys"
I see a lot of mirrorlist files in `/etc/pacman.d/`, should we replace all the configs?

2025-07-17 14:53 UTC, mudongliang commented
Let's first close this PR due to inactive progress

2025-07-17 14:53 UTC, closed without merging